### ISSUE TITLE
making functions instead of rewriting chunks of code

### ISSUE THREAD

**Issue by fedhere** [fedhere/detect120#10]
when we do things more than once, like the folding, it is good practice to write the code in a function instead of inline. that way if we fix a bug we only have to fix it once in the function, not 4 times in every chunk of code. for example, please move the piece of code that does the folding into a function def folding() which takes the frequency, and flux and timestamp arrays. Folding can return the new time and the new flux array, and even plot them, so then you can iterate as:

for key, value in flux35.iteritems():
   folded_35[key]['time'] ,    folded_35[key]['flux'] = folding (folded_35[key], runtime35[key])

**Comment by dm3805** [comment]
The folding definition is there already (I guess Shi's included it?), and it seems alright.
