### ISSUE TITLE
pickle the data so we can store it locally

### ISSUE THREAD

**Issue by fedhere** [fedhere/detect120#11]
please look at this notebook 
https://github.com/fedhere/detect120/blob/master/Shuttertest1_120_119Hz.ipynb
where i pickle the data. pickle is a binary python library. if we pickle the extracted photmetry then we can store the time series locally and run the notebook on our laptops, no need to be on compute

**Comment by fedhere** [comment]
i am assigning this to diogo since he seemed to have the harder time using the cluster. you ca reassign it if you think it is best.

**Comment by dm3805** [comment]
This is fine — I could login last night and will continue to work on this today. Tx!

**Comment by dm3805** [comment]
I've just included the pickling with the resized photos. I assumed we'd want to have pickles of the series prior to more significant transformations, so that's the reason I've included that at this particular stage. Please let me know if that's not ideal.

**Comment by fedhere** [comment]
ok, look at the code i sent you. you need to give the user the option to read in the data from the images, or from the pickle file. the way i had done it in the code i pointed you to is with a global variable 

REREAD=False

when REREAD is true you can get the time series from the images, and pickle them, otherwise you can read them from the pickled files (with pkl.load)

please add this functionality. then if we store the imasges on compute only, but the pickled files on our laptops, we can run the notebooks on our laptops.
