### ISSUE TITLE
let's curb insanities :) 

### ISSUE THREAD

**Issue by fedhere** [fedhere/detect120#12]
(1000_runtime)%(2_1/freq*1000) 

so here we have 2*1, which is 2, and we still multiply and divide by 1000. can you justify why you have not removes the 1000??

**Comment by fanshi118** [comment]
The function has just been updated. My previous concern was that we wanted to use microseconds as the unit of our x-axis, and removing the 1000 will result in seconds. Now I realize I can resolve this issue by returning 1000*(the original runtime)
