### ISSUE TITLE
PLEASE DO NOT COMMIT . (DOT) FILES

### ISSUE THREAD

**Issue by fedhere** [fedhere/detect120#13]
the .ipython_checkpoint folder was committed and gave me a terribly hard time when i was trying to push changes! please never do things like add *, and never commit executables either (the .pyc files) please remove them.

**Comment by fanshi118** [comment]
Sorry about giving you a hard time. I just removed the .pyc file and .ipython_checkpoint folder. Won't add \* next time :+1:

**Comment by fedhere** [comment]
or you can create a .gitignore file with the extensions of the files you
never want to be added.
i still do not recommand add \* or commit without specifying what. the first
one is a bad habit that exposes you to check in data, large files, and
especially considering you are likely to work with protected data you
should not get used to it. the latter is bad because you want each of your
commits to have a sensible message logged with it, and committing
everything with the same message is rarely the proper way to document your
changes

(notice that the file name must start with a '.', but the attachment i have
here does not)

On Wed, Mar 23, 2016 at 9:03 AM, Shi Fan notifications@github.com wrote:

> Sorry about giving you a hard time. I just removed the .pyc file and
> .ipython_checkpoint folder. Won't add \* next time [image: :+1:]
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/fedhere/detect120/issues/13#issuecomment-200337135

## 

 /|/\
   |\*  Please consider the environment before printing this e-mail

**Comment by fanshi118** [comment]
okay, got it. I'll try to commit one-by-one to document the workflow
