### ISSUE TITLE
Simulated signal

### ISSUE THREAD

**Issue by fedhere** [fedhere/detect120#3]
hi diogo. the signal that we simulate should be as simple as possible. then when we compare it to the observed signal the ration of the two can be trivially interpreted. 

a square wave is the simplest signal. it is also close to the electrical signal we are inputting.  a sign wave is also simple. they are simple in the sense that they are symmetric, and they can be described analytically.

now: the signal you generate, at the origin, is a sine wave, but look at the plot. 
![scywnrs4gv 0aau jksvjzm5yzrarkk7659j5fovqee ondixag8azzxxt2cy85a7nzoztcazjnxiygqymcwysmpi 0azdkzzdkyy8hkmpnmmrjjygqymcwysmpizdkzzdkyy8hkmpnmmrjjygqymcwysmpizdkzzdl lw5k 0ags3kf9znaaaaaelftksuqmcc 0a](https://cloud.githubusercontent.com/assets/1696902/13025618/eb7cbf68-d1d9-11e5-8e55-a7bc4b4dd2a6.png) you are chopping your sine wave so that it is a sign at the top half, and a square at the bottom! that is not a simple signal (which is why i made you plot it). makes sense?

the bad line of code is this: 
    sine[i] = [0 if f<0 else f for f in sine[i]]
why are you doing it?

**Comment by dm3805** [comment]
Thanks for the comments! I'll incorporate the square waves. As for the bottom of the sine waves, I'd assumed that the shutter would be closed in the bottom section of the waves, and therefore that the flux would be zero at these points. I still need to understand better how the shutter impacts the flux, but I'll fix the code in the meanwhile.

**Comment by fedhere** [comment]
ok, i see.

well understanding how the shutter impacts the flux is the goal here, so we
need a simple signal in to understand what the differences from the
expectation is. we cant make assumptions at this stage yet.

On Sat, Feb 13, 2016 at 11:33 AM, diogomiura notifications@github.com
wrote:

> Thanks for the comments! I'll incorporate the square waves. As for the
> bottom of the sine waves, I'd assumed that the shutter would be closed in
> bottom section of the waves, and therefore that the flux would be zero at
> these points. I still need to understand better how the shutter impacts the
> flux, but I'll fix the code in the meanwhile.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fedhere/detect120/issues/3#issuecomment-183699815.

## 

 /|/\
   |\*  Please consider the environment before printing this e-mail
