### ISSUE TITLE
shutter speed for 199.75

### ISSUE THREAD

**Issue by fedhere** [fedhere/detect120#4]
your shutter speed of 119.75  is referred to in your code with 11975. that is ok when you used this as a dic keyword and when you create the name string but it is WRONG to pass it as the cadence: the cadence has to be 119.75!

**Comment by fedhere** [comment]
also to see the effects of integration you need to sample the square wave more finely

i made some changes to the code, check them out

**Comment by dm3805** [comment]
Just checked - thanks for the insightful comments (particularly for showing me one new way to avoid loops!) And sorry for the stupid 119.75 mistake. :-/
